# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/osad/Рабочий стол/qkd/qldpc-toCmake"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/osad/Рабочий стол/qkd/qldpc-toCmake"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/osad/Рабочий стол/qkd/qldpc-toCmake/CMakeFiles" "/home/osad/Рабочий стол/qkd/qldpc-toCmake/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/osad/Рабочий стол/qkd/qldpc-toCmake/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testLDPC

# Build rule for target.
testLDPC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testLDPC
.PHONY : testLDPC

# fast build rule for target.
testLDPC/fast:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/build
.PHONY : testLDPC/fast

#=============================================================================
# Target rules for targets named libLDPC

# Build rule for target.
libLDPC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libLDPC
.PHONY : libLDPC

# fast build rule for target.
libLDPC/fast:
	$(MAKE) -f libLDPC/CMakeFiles/libLDPC.dir/build.make libLDPC/CMakeFiles/libLDPC.dir/build
.PHONY : libLDPC/fast

LDPC-4Qt/ldpc4qt.o: LDPC-4Qt/ldpc4qt.cpp.o
.PHONY : LDPC-4Qt/ldpc4qt.o

# target to build an object file
LDPC-4Qt/ldpc4qt.cpp.o:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/LDPC-4Qt/ldpc4qt.cpp.o
.PHONY : LDPC-4Qt/ldpc4qt.cpp.o

LDPC-4Qt/ldpc4qt.i: LDPC-4Qt/ldpc4qt.cpp.i
.PHONY : LDPC-4Qt/ldpc4qt.i

# target to preprocess a source file
LDPC-4Qt/ldpc4qt.cpp.i:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/LDPC-4Qt/ldpc4qt.cpp.i
.PHONY : LDPC-4Qt/ldpc4qt.cpp.i

LDPC-4Qt/ldpc4qt.s: LDPC-4Qt/ldpc4qt.cpp.s
.PHONY : LDPC-4Qt/ldpc4qt.s

# target to generate assembly for a file
LDPC-4Qt/ldpc4qt.cpp.s:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/LDPC-4Qt/ldpc4qt.cpp.s
.PHONY : LDPC-4Qt/ldpc4qt.cpp.s

libLDPC/libldpc.o: libLDPC/libldpc.cpp.o
.PHONY : libLDPC/libldpc.o

# target to build an object file
libLDPC/libldpc.cpp.o:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/libLDPC/libldpc.cpp.o
.PHONY : libLDPC/libldpc.cpp.o

libLDPC/libldpc.i: libLDPC/libldpc.cpp.i
.PHONY : libLDPC/libldpc.i

# target to preprocess a source file
libLDPC/libldpc.cpp.i:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/libLDPC/libldpc.cpp.i
.PHONY : libLDPC/libldpc.cpp.i

libLDPC/libldpc.s: libLDPC/libldpc.cpp.s
.PHONY : libLDPC/libldpc.s

# target to generate assembly for a file
libLDPC/libldpc.cpp.s:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/libLDPC/libldpc.cpp.s
.PHONY : libLDPC/libldpc.cpp.s

testLDPC.o: testLDPC.cpp.o
.PHONY : testLDPC.o

# target to build an object file
testLDPC.cpp.o:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/testLDPC.cpp.o
.PHONY : testLDPC.cpp.o

testLDPC.i: testLDPC.cpp.i
.PHONY : testLDPC.i

# target to preprocess a source file
testLDPC.cpp.i:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/testLDPC.cpp.i
.PHONY : testLDPC.cpp.i

testLDPC.s: testLDPC.cpp.s
.PHONY : testLDPC.s

# target to generate assembly for a file
testLDPC.cpp.s:
	$(MAKE) -f CMakeFiles/testLDPC.dir/build.make CMakeFiles/testLDPC.dir/testLDPC.cpp.s
.PHONY : testLDPC.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testLDPC"
	@echo "... libLDPC"
	@echo "... LDPC-4Qt/ldpc4qt.o"
	@echo "... LDPC-4Qt/ldpc4qt.i"
	@echo "... LDPC-4Qt/ldpc4qt.s"
	@echo "... libLDPC/libldpc.o"
	@echo "... libLDPC/libldpc.i"
	@echo "... libLDPC/libldpc.s"
	@echo "... testLDPC.o"
	@echo "... testLDPC.i"
	@echo "... testLDPC.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

